version: "3"
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - clientes-compose-network
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vinicius123
      MYSQL_DATABASE: produtos_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - clientes-compose-network
    depends_on:
      - db
    ports:
      - "5000:80"

  minha-api:
    image: viniciuscfn/api-azure:latest
    networks:
      - clientes-compose-network
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:

networks:
  clientes-compose-network:
    driver: bridge
