
server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/produtos_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root123

    jpa:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.ddl-auto: update
      hibernate:
        jdbc: time_zone = TimeZone
      show-sql: true